version: '3.9'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/greenroute
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: super-secret-value
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greenroute
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
